# permissions for end users to view hascomponentdetectionqueries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hascomponentdetectionquery-viewer-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - hascomponentdetectionqueries
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - hascomponentdetectionqueries/status
  verbs:
  - get
