# permissions for end users to edit hascomponentdetectionqueries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hascomponentdetectionquery-editor-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - hascomponentdetectionqueries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - hascomponentdetectionqueries/status
  verbs:
  - get
